Repository FelixAlexK/PawSwipe, pull requests merged in 2023-04, with the labels that each got.

#4 Feature fkuhbier petprofil
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/PetProfileActivity.kt
  app/src/main/res/layout/activity_pet_profil.xml
  app/src/main/res/values/genders.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#2 added ui for ChatActivity and SettingsActivity
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/ChatActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/SettingsActivity.kt
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/menu/menu_home.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#7 Feature fkuhbier api into development
  app/build.gradle
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/AnimalProfileApi.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/UserProfileApi.kt
Labels: enhancement

#10 feature-fkuhbier-api into development
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/AnimalProfileApi.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/UserProfileApi.kt
Labels: enhancement

#11 Feature fkuhbier loginui into development
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#13 Create README.md
  README.md
Labels: documentation

#12 Feature fkuhbier petprofile into development
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/DatePickerFragment.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/PetProfileActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/AnimalProfileApi.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/UserProfileApi.kt
  app/src/main/res/layout/activity_pet_profil.xml
  app/src/main/res/values/date_format.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#14 Feature fkuhbier petprofile into development
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/PetProfileActivity.kt
Labels: duplicate

#17 merge feature-lkalmbach-settingsui branch into development
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/ChatActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/EditAnimalActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/MainActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/MatchActivityNico.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/SettingsActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/ViewPagerAdapter.kt
  app/src/main/res/drawable/dislike_x.png
  app/src/main/res/layout/activity_animal_list.xml
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_create_user.xml
  app/src/main/res/layout/activity_edit_animal.xml
  app/src/main/res/layout/activity_match.xml
  app/src/main/res/layout/activity_pet_profil.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/image_slider_item.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#16 Colors adjusted to Pawswipe "Orange"
  app/src/main/res/layout/activity_animal_list.xml
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_match.xml
  app/src/main/res/layout/activity_register_shelter_account.xml
  app/src/main/res/layout/activity_register_user.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#18 feature-fkuhbier-delete_user into development
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/CreateUserProfileActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/EditAnimalActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/PetProfileActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/SettingsActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/UserProfileApi.kt
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_create_user_profile.xml
  app/src/main/res/layout/activity_edit_animal.xml
  app/src/main/res/layout/activity_pet_profil.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
