Repository FelixAlexK/PawSwipe, pull requests merged in 2023-07, with the labels that each got.

#68 Feature fkuhbier detail view dislike
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/AnimalListActivity.kt
  app/src/main/res/layout/activity_detailed_animal_profile.xml
Labels: enhancement

#69 Feature fkuhbier filter api
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/MainActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/filter/FilterApi.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/filter/FilterEnum.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/filter/FilterException.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/filter/FilterInterface.kt
  app/src/main/res/layout/activity_animal_service.xml
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_detailed_animal_profile.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#71 Feature fkuhbier filter api
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/filter/FilterApi.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/utils/BitmapScaler.kt
Labels: update

#74 user cant create/edit animals
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/AnimalListActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/AnimalServiceActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/ChatActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/MatchActivity.kt
  app/src/main/res/menu/menu_user.xml
Labels: enhancement

#73 Bugfixes eccolak matchactivity into dev
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/CardAdapter.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/FilterActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/MatchActivity.kt
  app/src/main/res/layout/activity_match.xml
  app/src/main/res/values/strings.xml
Labels: bug

#78 Update README.md
  README.md
Labels: documentation

#79 fix.fkuhbier into development
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/AnimalServiceActivity.kt
  app/src/main/res/layout/activity_edit_animal.xml
  app/src/main/res/layout/activity_edit_shelter.xml
Labels: bug

#80 Update README.md
  README.md
Labels: documentation
