Repository FelixAlexK/PawSwipe, pull requests merged in 2023-06, with the labels that each got.

#43 added spinner for species and breeds in FilterActivity and EditAnimal…
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/EditAnimalActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/FilterActivity.kt
  app/src/main/res/layout/activity_edit_animal.xml
  app/src/main/res/layout/activity_filter.xml
  app/src/main/res/values/bird.xml
  app/src/main/res/values/breed.xml
  app/src/main/res/values/cat.xml
  app/src/main/res/values/dog.xml
  app/src/main/res/values/reptile.xml
  app/src/main/res/values/smallAnimal.xml
  app/src/main/res/values/species.xml
Labels: enhancement

#45 Feature fkuhbier update api swp23 mtv 52
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/animal/AnimalProfileApi.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/animal/AnimalProfileInterface.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/data/AnimalProfileData.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/data/ProfileData.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/user/ProfileApi.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/user/ProfileInterface.kt
Labels: update

#46 Testing fkuhbier swp23 mtv 56 into development
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/AnimalListActivityNico.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/AnimalServiceActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/ChatActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/CreateShelterActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/CreateUserProfileActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/DatePickerFragment.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/EditAnimalActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/FilterActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/LoginActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/MainActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/MatchActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/PetProfileActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/RegisterAccountActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/SettingsActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/animal/AnimalProfileApi.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/data/ProfileData.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/user/ProfileApi.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/user/ProfileInterface.kt
  app/src/main/res/layout/activity_match.xml
  app/src/main/res/values/date_format.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#47 Feature lkalmbach UI swp23 mtv 45
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/EditAnimalActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/FilterActivity.kt
  app/src/main/res/values/genders.xml
Labels: update

#48 changed DatePicker calendar color to orange
  app/src/main/res/values/themes.xml
Labels: update

#49 Feature fkuhbier update api swp23 mtv 52 into development
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/data/LikeData.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/like/LikeApi.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/like/LikeInterface.kt
Labels: update

#55 added method for calculating distance between two locations
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/DistanceHelper.kt
Labels: enhancement

#56 Feature eccolak pflichtfelder swp23 mtv 63 into development
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/CreateShelterActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/CreateUserProfileActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/PetProfileActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/RegisterAccountActivity.kt
  app/src/main/res/layout/activity_create_shelter.xml
  app/src/main/res/layout/activity_create_user_profile.xml
  app/src/main/res/layout/activity_pet_profil.xml
  app/src/main/res/layout/activity_register_account.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, update

#57 Feature fkuhbier like UI swp23 mtv 53
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/AnimalListActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/AnimalListActivityNico.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/AnimalServiceActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/ChatActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/CreateShelterActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/CreateUserProfileActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/EditAnimalActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/FilterActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/MatchActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/PetProfileActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/SettingsActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/ViewPagerAdapter.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/animal/AnimalProfileApi.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/animal/AnimalProfileInterface.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/data/AnimalProfileData.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/data/ProfileData.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/like/LikeApi.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/like/LikeInterface.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/user/ProfileApi.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/user/ProfileInterface.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/utils/AnimalAdapter.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/utils/AnimalItem.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/utils/AnimalViewHolder.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/utils/Base64Utils.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/utils/BitmapScaler.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/utils/DatePickerFragment.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/utils/ViewPagerAdapter.kt
  app/src/main/res/drawable/dislike.png
  app/src/main/res/drawable/dislike_x.png
  app/src/main/res/drawable/heart_liked_small.png
  app/src/main/res/drawable/heart_unliked_small.png
  app/src/main/res/drawable/love.png
  app/src/main/res/layout/activity_animal_list.xml
  app/src/main/res/layout/activity_create_shelter.xml
  app/src/main/res/layout/activity_create_user_profile.xml
  app/src/main/res/layout/activity_edit_animal.xml
  app/src/main/res/layout/activity_filter.xml
  app/src/main/res/layout/activity_match.xml
  app/src/main/res/layout/activity_pet_profil.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/animal_item.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#58 update-fkuhbier-api-lat-long-SWP23MTV-74 into development
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/CreateShelterActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/CreateUserProfileActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/data/ProfileData.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/user/ProfileApi.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/user/ProfileInterface.kt
Labels: update

#59 Feature eccolak no match for shelter swp23 mtv 70 into Development
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/AnimalListActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/AnimalServiceActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/ChatActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/CreateShelterActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/EditAnimalActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/EditShelterActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/FilterActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/LoginActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/MatchActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/PetProfileActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/SettingsActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/utils/AppData.kt
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi-v33/ic_launcher.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, update

#63 Feature fkuhbier shelter animal list swp23 mtv 76 into development
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/AnimalListActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/PetProfileActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/animal/AnimalProfileApi.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/animal/AnimalProfileInterface.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/api/data/AnimalProfileData.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/utils/AnimalAdapter.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/utils/AnimalItem.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/utils/AnimalViewHolder.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#65 Feature fkuhbier display animal profile swp23 mtv 75 into development
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/AnimalListActivity.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/utils/AnimalAdapter.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/utils/AnimalItem.kt
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/utils/Base64Utils.kt
  app/src/main/res/layout/activity_animal_list.xml
  app/src/main/res/layout/activity_detailed_animal_profile.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#67 Feature nwendler login discriminator
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#66 Feature fkuhbier suppress darkmode
  app/src/main/java/de/hhn/softwarelabor/pawswipeapp/MainActivity.kt
  app/src/main/res/layout/activity_detailed_animal_profile.xml
  app/src/main/res/values/themes.xml
Labels: enhancement
